# Generated by Django 5.1.1 on 2025-08-17 00:57

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("prep_time_minutes", models.PositiveIntegerField(db_index=True)),
                ("cook_time_minutes", models.PositiveIntegerField(db_index=True)),
                ("servings", models.PositiveIntegerField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("cuisine", models.CharField(db_index=True, max_length=100)),
                ("calories_per_serving", models.PositiveIntegerField(db_index=True)),
                ("image", models.URLField()),
                ("rating", models.FloatField(db_index=True)),
                ("review_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "meal_types",
                    models.ManyToManyField(db_index=True, to="recipe.mealtype"),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveIntegerField()),
                ("description", models.TextField()),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructions",
                        to="recipe.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipe.recipe",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["difficulty", "cuisine"], name="recipe_reci_difficu_d46f90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["prep_time_minutes", "cook_time_minutes"],
                name="recipe_reci_prep_ti_aa4a7c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["rating", "review_count"], name="recipe_reci_rating_f64fdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instruction",
            index=models.Index(
                fields=["recipe", "step_number"], name="recipe_inst_recipe__f3c9bf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="instruction",
            unique_together={("recipe", "step_number")},
        ),
        migrations.AlterUniqueTogether(
            name="ingredient",
            unique_together={("recipe", "name")},
        ),
    ]
